version: '3.8'

networks:
  sql-assistant-network:
    driver: bridge

volumes:
  sqlite_data:

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    depends_on:
      sqlite:
        condition: service_healthy
    networks:
      - sql-assistant-network

  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite-db
    ports:
      - "5432:5432"
    volumes:
      - ./sqlite_data/car_db.sql:/db/car_db.sql
      - ./sqlite_data:/db
    entrypoint: >
      sh -c "sqlite3 /db/cars.db << /db/car_db.sql && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "sqlite3", "/db/cars.db", ".tables"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sql-assistant-network
