FROM alpine:latest

# Install SQLite
RUN apk update && apk add --no-cache sqlite && \
    mkdir /db && \
    touch /db/car_db.sqlite

# Copy the initialization script and SQL file
COPY ./scripts/init-cars-db.sh /db

# Run the initialization script
RUN /db/init-cars-db.sh

CMD ["sqlite3", "/db/car_db.sqlite"]